### ISSUE TITLE
ValueError: need more than 1 value to unpack in line 74, in RetinaNet

### ISSUE THREAD

**Issue by mubastan** [delftrobotics/keras-retinanet#1]
Is this implementation complete and working?

I get this error when I try to run train.py:

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    model = create_model()
  File "train.py", line 17, in create_model
    return ResNet50RetinaNet([image, im_info, gt_boxes])
  File "build/bdist.linux-x86_64/egg/keras_retinanet/models/resnet.py", line 128, in ResNet50RetinaNet
  File "build/bdist.linux-x86_64/egg/keras_retinanet/models/resnet.py", line 74, in RetinaNet
ValueError: need more than 1 value to unpack
```
I run setup.py install, which installed keras-resnet 0.0.7 from https://pypi.python.org/simple/keras-resnet/

**Comment by mubastan** [comment]
The RetinaNet paper mentions a new initialization strategy, without which the training does not work, as they say..
There is a PyTorch implementation here https://github.com/kuangliu/pytorch-retinanet, but I have not tried it yet.

**Comment by hgaiser** [comment]
I tried that initialization but it didn't seem to work for me. It's very well possible that I misinterpreted their paper in some way, but it's difficult to localize where the training is failing.
