### ISSUE TITLE
train_pascal.py import error

### ISSUE THREAD

**Issue by jwnsu** [delftrobotics/keras-retinanet#32]
pulled latest codes and got following simple import error during training (env: keras 2.0.8/tensorflow 1.2)
"Traceback (most recent call last):
  File "examples/itrain.py", line 23, in <module>
    from keras_retinanet.models import ResNet50RetinaNet
  File "/home/dsu/ai/krn/keras_retinanet/__init__.py", line 5, in <module>
    from . import models
  File "/home/dsu/ai/krn/keras_retinanet/models/__init__.py", line 3, in <module>
    from .resnet import ResNet50RetinaNet
  File "/home/dsu/ai/krn/keras_retinanet/models/resnet.py", line 18, in <module>
    import keras_resnet.models
ImportError: No module named keras_resnet.models"

cannot find keras_resnet in keras-retinanet or keras.

Thanks.

**Comment by jwnsu** [comment]
resolved by install separate package: "pip install keras-resnet". It's good for readme to include this step.

**Comment by mhwilder** [comment]
did you run the setup script?
    `sudo python setup.py install`
I believe that takes care of that.
