### ISSUE TITLE
Training on MSCOCO fails

### ISSUE THREAD

**Issue by gat3way** [delftrobotics/keras-retinanet#40]
I did a git pull of the latest code today and tried to train on mscoco. The new pyramid layers apparently have some issue though :( Please take a look at the following log:

> Total memory: 10.91GiB
Free memory: 9.84GiB
2017-11-07 11:04:29.832092: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2017-11-07 11:04:29.832105: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2017-11-07 11:04:29.832119: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0)
Creating model, this may take a second...
Traceback (most recent call last):
  File "examples/train_coco.py", line 60, in <module>
    model = create_model(weights=args.weights)
  File "examples/train_coco.py", line 38, in create_model
    return ResNet50RetinaNet(image, num_classes=90, weights=weights)
  File "/data/cnn/keras/keras-retinanet/keras_retinanet/models/resnet.py", line 38, in ResNet50RetinaNet
    model = keras_retinanet.models.retinanet_bbox(inputs=inputs, backbone=resnet, *args, **kwargs)
  File "/data/cnn/keras/keras-retinanet/keras_retinanet/models/retinanet.py", line 193, in retinanet_bbox
    model = retinanet(inputs=inputs, num_classes=num_classes, *args, **kwargs)
  File "/data/cnn/keras/keras-retinanet/keras_retinanet/models/retinanet.py", line 175, in retinanet
    submodels = default_submodels(num_classes, anchor_parameters)
  File "/data/cnn/keras/keras-retinanet/keras_retinanet/models/retinanet.py", line 139, in default_submodels
    default_regression_model(anchor_parameters.num_anchors()),
  File "/data/cnn/keras/keras-retinanet/keras_retinanet/models/retinanet.py", line 87, in default_regression_model
    outputs = keras.layers.Reshape((-1, 4), name='pyramid_regression_reshape')(outputs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 602, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 391, in call
    target_shape = self.compute_output_shape(input_shape)[1:]
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 376, in compute_output_shape
    input_shape[1:], self.target_shape)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 364, in _fix_unknown_dimension
    original = np.prod(input_shape, dtype=int)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 2498, in prod
    out=out, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py", line 35, in _prod
    return umr_prod(a, axis, dtype, out, keepdims)
TypeError: long() argument must be a string or a number, not 'NoneType'

**Comment by hgaiser** [comment]
I see you're using `python2.7`. This package is developed using `python3.6`. I try to keep every code python2/3 compatible, but sometimes an error slips through. Can you test if the training process works with python3? It'd give me some more insight in what is going wrong.

**Comment by gat3way** [comment]
Found it out, python2.7 is fine actually, turned out it requires keras 2.0.9 and mine was 2.0.8

**Comment by sorinpanduru** [comment]
Yep, had the same problem myself. upgrading from 2.0.8 to 2.0.9 fixed it.

**Comment by hgaiser** [comment]
Ah right this is for the `Reshape` layer! I didn't recognize it at first glance. I'll consider this issue as resolved then.

ps. keras 2.0.9 seems to have a few small bugs, nothing fatal, but 2.0.10 should be released sometime soon.
